/*
 * TIMER0_CTC_64_PRESCALING.c
 * BLINK AN LED WITH 5 sec DELAY BY USING CTC AND 64 PRESCALING.
 * Created: 22-09-2025 14:15:31
 * Author : ANAGHA
 */ 


#define F_CPU 16000000UL
#include <avr/io.h>

int main(void)
{
    DDRB |= (1 << DDB5);  //SET DDB5 AS OUTPUT FOR LED.
	TCCR0A |= (1 << WGM01); // CTC MODE 
	OCR0A = 200; // SETPOINT,ANY VALUE LESS THAN 255  SINCE IT'S AN 8 BIT REGISTER.
	TCNT0 = 0; //SET INITIAL VALUE OF TIMER,TCNT0 AS 0. 
	TCCR0B |= (1 << CS00) | (1 << CS01); // 64 PRESCALING 
	TIFR0 |= (1 << OCF0A); //WRITING 1 TO OCF0A BIT OF TIFR0 REGISTER TO RESET IT.
    
	while (1)
	{
		PORTB ^= (1 << PORTB5);
		for (long int i = 0;i < 6250;i++)  // FOR 5 sec DELAY,LOOP HAS TO RUN 6250 TIMES IN 64 PRESCALING.
		{
			while(!(TIFR0 &(1 << OCF0A))) //FOR GETTING 12.5us DELAY,KEEP LOOPING UNTIL OCF0A BECOMES 1.
			{
				
			}
			TIFR0 |= (1 << OCF0A); //WRITING 1 TO OCF0A BIT OF TIFR0 REGISTER TO RESET IT.
		}
		
	}
	
}





